package org.fbi.fskfq.repository.model;

import java.math.BigDecimal;

public class FsKfqPaymentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String chrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String billtypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String billtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String ienCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String ienName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String consignIenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String consignIenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String pmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String pmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String chequeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String payerbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String payeraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String receiverbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String receiveraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String verifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String rgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String receivetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String inputername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String isConsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String lateflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String nosourceIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String supplytempletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String bankIndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String incomestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String setYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String routeUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private BigDecimal billMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String bankUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String canceldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_BANKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String operBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String hostBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String hostChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String fbBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String fbChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String archiveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_BANKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String archiveOperBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String archiveOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_DATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String archiveOperDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_TIME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String archiveOperTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    private String hostAckFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @param pkid the value for FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getChrId() {
        return chrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @param chrId the value for FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setChrId(String chrId) {
        this.chrId = chrId == null ? null : chrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBilltypeCode() {
        return billtypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @param billtypeCode the value for FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBilltypeCode(String billtypeCode) {
        this.billtypeCode = billtypeCode == null ? null : billtypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBilltypeName() {
        return billtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @param billtypeName the value for FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBilltypeName(String billtypeName) {
        this.billtypeName = billtypeName == null ? null : billtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @param billNo the value for FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @param makedate the value for FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setMakedate(String makedate) {
        this.makedate = makedate == null ? null : makedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getIenCode() {
        return ienCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @param ienCode the value for FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setIenCode(String ienCode) {
        this.ienCode = ienCode == null ? null : ienCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getIenName() {
        return ienName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @param ienName the value for FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setIenName(String ienName) {
        this.ienName = ienName == null ? null : ienName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getConsignIenCode() {
        return consignIenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @param consignIenCode the value for FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setConsignIenCode(String consignIenCode) {
        this.consignIenCode = consignIenCode == null ? null : consignIenCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getConsignIenName() {
        return consignIenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @param consignIenName the value for FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setConsignIenName(String consignIenName) {
        this.consignIenName = consignIenName == null ? null : consignIenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getPmCode() {
        return pmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @param pmCode the value for FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setPmCode(String pmCode) {
        this.pmCode = pmCode == null ? null : pmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @param pmName the value for FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setPmName(String pmName) {
        this.pmName = pmName == null ? null : pmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getChequeNo() {
        return chequeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @param chequeNo the value for FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo == null ? null : chequeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @param payer the value for FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getPayerbank() {
        return payerbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @param payerbank the value for FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setPayerbank(String payerbank) {
        this.payerbank = payerbank == null ? null : payerbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getPayeraccount() {
        return payeraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @param payeraccount the value for FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setPayeraccount(String payeraccount) {
        this.payeraccount = payeraccount == null ? null : payeraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @param receiver the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getReceiverbank() {
        return receiverbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @param receiverbank the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setReceiverbank(String receiverbank) {
        this.receiverbank = receiverbank == null ? null : receiverbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getReceiveraccount() {
        return receiveraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @param receiveraccount the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setReceiveraccount(String receiveraccount) {
        this.receiveraccount = receiveraccount == null ? null : receiveraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getVerifyNo() {
        return verifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @param verifyNo the value for FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setVerifyNo(String verifyNo) {
        this.verifyNo = verifyNo == null ? null : verifyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getRgCode() {
        return rgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @param rgCode the value for FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setRgCode(String rgCode) {
        this.rgCode = rgCode == null ? null : rgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getReceivetype() {
        return receivetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @param receivetype the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setReceivetype(String receivetype) {
        this.receivetype = receivetype == null ? null : receivetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getInputername() {
        return inputername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @param inputername the value for FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setInputername(String inputername) {
        this.inputername = inputername == null ? null : inputername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getIsConsign() {
        return isConsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @param isConsign the value for FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setIsConsign(String isConsign) {
        this.isConsign = isConsign == null ? null : isConsign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getLateflag() {
        return lateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @param lateflag the value for FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setLateflag(String lateflag) {
        this.lateflag = lateflag == null ? null : lateflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getNosourceIds() {
        return nosourceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @param nosourceIds the value for FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setNosourceIds(String nosourceIds) {
        this.nosourceIds = nosourceIds == null ? null : nosourceIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getSupplytempletId() {
        return supplytempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @param supplytempletId the value for FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setSupplytempletId(String supplytempletId) {
        this.supplytempletId = supplytempletId == null ? null : supplytempletId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @param remark the value for FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBankIndate() {
        return bankIndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @param bankIndate the value for FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBankIndate(String bankIndate) {
        this.bankIndate = bankIndate == null ? null : bankIndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getIncomestatus() {
        return incomestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @param incomestatus the value for FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setIncomestatus(String incomestatus) {
        this.incomestatus = incomestatus == null ? null : incomestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getSetYear() {
        return setYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @param setYear the value for FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setSetYear(String setYear) {
        this.setYear = setYear == null ? null : setYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getRouteUserCode() {
        return routeUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @param routeUserCode the value for FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setRouteUserCode(String routeUserCode) {
        this.routeUserCode = routeUserCode == null ? null : routeUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @param license the value for FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @param businessId the value for FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public BigDecimal getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @param billMoney the value for FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBillMoney(BigDecimal billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @param bankUser the value for FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @param bankNo the value for FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getCanceldate() {
        return canceldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @param canceldate the value for FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setCanceldate(String canceldate) {
        this.canceldate = canceldate == null ? null : canceldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_BANKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_BANKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getOperBankid() {
        return operBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_BANKID
     *
     * @param operBankid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_BANKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setOperBankid(String operBankid) {
        this.operBankid = operBankid == null ? null : operBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ID
     *
     * @param operId the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_DATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_DATE
     *
     * @param operDate the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_DATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_TIME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_TIME
     *
     * @param operTime the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_TIME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getHostBookFlag() {
        return hostBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @param hostBookFlag the value for FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setHostBookFlag(String hostBookFlag) {
        this.hostBookFlag = hostBookFlag == null ? null : hostBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getHostChkFlag() {
        return hostChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @param hostChkFlag the value for FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setHostChkFlag(String hostChkFlag) {
        this.hostChkFlag = hostChkFlag == null ? null : hostChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getFbBookFlag() {
        return fbBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @param fbBookFlag the value for FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setFbBookFlag(String fbBookFlag) {
        this.fbBookFlag = fbBookFlag == null ? null : fbBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getFbChkFlag() {
        return fbChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @param fbChkFlag the value for FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setFbChkFlag(String fbChkFlag) {
        this.fbChkFlag = fbChkFlag == null ? null : fbChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getArchiveFlag() {
        return archiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @param archiveFlag the value for FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setArchiveFlag(String archiveFlag) {
        this.archiveFlag = archiveFlag == null ? null : archiveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_BANKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_BANKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getArchiveOperBankid() {
        return archiveOperBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_BANKID
     *
     * @param archiveOperBankid the value for FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_BANKID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setArchiveOperBankid(String archiveOperBankid) {
        this.archiveOperBankid = archiveOperBankid == null ? null : archiveOperBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getArchiveOperId() {
        return archiveOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_ID
     *
     * @param archiveOperId the value for FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_ID
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setArchiveOperId(String archiveOperId) {
        this.archiveOperId = archiveOperId == null ? null : archiveOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_DATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_DATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getArchiveOperDate() {
        return archiveOperDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_DATE
     *
     * @param archiveOperDate the value for FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_DATE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setArchiveOperDate(String archiveOperDate) {
        this.archiveOperDate = archiveOperDate == null ? null : archiveOperDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_TIME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_TIME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getArchiveOperTime() {
        return archiveOperTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_TIME
     *
     * @param archiveOperTime the value for FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_OPER_TIME
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setArchiveOperTime(String archiveOperTime) {
        this.archiveOperTime = archiveOperTime == null ? null : archiveOperTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public String getHostAckFlag() {
        return hostAckFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @param hostAckFlag the value for FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Tue Dec 24 11:35:41 CST 2013
     */
    public void setHostAckFlag(String hostAckFlag) {
        this.hostAckFlag = hostAckFlag == null ? null : hostAckFlag.trim();
    }
}